### PR TITLE
Fix #2974 and #2816: Enable custom menu templates, and prevent duplicate items in column menu.

### LINKED ISSUE #2974: ColumnMenus: if open second menu without closing first, get duplicate items
Open the first menu, then open the second (or last) without closing the first.
http://plnkr.co/edit/mtEO8fkK6ohqQDpgbyGE?p=preview

### PR DESCRIPTION
**Pull request by farooqu**
This reverts a reversion to bring back the custom menu template functionality from 2.x. It also fixes the bug introduced by that original commit which necessitated the reversion, by putting the show-menu broadcast in a timeout. The ng-if="shown" for uiGridMenu.html had a delay due to $animate. As a result, even though shown was being set to false, the menu was not being removed from the DOM before it was added back in. This caused the previous elements to stick around.

[Review on Reviewable](https://reviewable.io/reviews/angular-ui/ng-grid/3049)

### CODE REVIEW

**Comment by farooqu** [comment]
http://plnkr.co/edit/cFAciH?p=preview Plunker updated with the ui-grid.js from my fork.

**Comment by PaulL1** [comment]
OK, looks like it works.  But I'm not clear why it's needed now when it wasn't needed before - is it because the templates are getting retrieved or something?  I'm nervous that the $timeout might fix it in this specific instance, but perhaps if the template retrieve were slower it might not work.

The documentation on each option points to the footer tutorial for more information - is there some more detail somewhere about what these templates can be used for?

**Comment by farooqu** [comment]
I'm not sure why it would be needed now but wasn't in the past. The uiGridMenu showMenu and hideMenu methods both have a timeout to wait a digest cycle for the ng-if to be removed. The behavior I was seeing when debugging was that even though shown in uiGridMenu was being set to false, it was being re-set to true due to the $scope.$broadcast('show menu') before the digest cycle could apply the ng-if and remove the old menu items from the DOM.

**Comment by farooqu** [comment]
Regarding the documentation, that was an oversight in copy pasting the footer doc. I'll try and see if I can get some documentation added this weekend.

Our primary use case was to override the menu button's toggle method to expand it to include the ability to close the menu using the "ESC" key, as well as to modify the look of the menu to display a check-box with the label next to each item.

**Comment by tuhoojabotti** [comment]
Would be great to see this option. We have styled the grid to match our material design app, but it would be nice to be able to override the menu to use material components.

**Comment by mportuga** [comment]
@farooqu You appear to have some merge conflicts. Are you still interested in merging this? If so, would you mind resolving the conflicts so that I or someone else can  review it now?

**Comment by mportuga** [comment]
Closing due to inactivity.

**Pull request closed without merging**
