### PR TITLE
Cellnav onnavigate called too often

### PR DESCRIPTION
**Pull request by lvostinar**
this is a pull request for: https://github.com/angular-ui/ui-grid/issues/4835

### CODE REVIEW

**Comment by imbalind** [comment]
@lvostinar the code looks gode, I have to ask you to merge master into your branch and squash your commits into one, then I'll merge this. Thanks!

**Comment by B8li** [comment]
Hi, 
I had issues with editing dropdown in first row when rowHeight is < 30px (check #4799, #4710 and probably some other reported issues). 
This fix also fixes all this problems. Maybe someone with more knowlage of the code can check the issues and add close them if they are fixed with this same commit-looks to me that they are fixed with this PR.

**Comment by kylej-89** [comment]
When will this fix be in? I need it asap :-/

**Comment by lvostinar** [comment]
The fix is already merged. Should be present in latest release.

**Comment by HaroldStruwig** [comment]
#4835 is still open

**Pull request merged**
