### PR TITLE
Fix issue with space after the last table row

### PR DESCRIPTION
**Pull request by Nilanno**
Can't find out a reason of issue, but it's reproduced easily in our application. This code fixes it.

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Can you describe the issue in more detail? Include screenshots a GIF or a plunker demo.

**Comment by Nilanno** [comment]
Here is an image - http://prntscr.com/9ehrsv

Behavior was pretty strange: if scroll had 50% of container scroll at beginning, he was smaller and smaller with scroll down so at the end of the scroll he had height near a half of initial.
So it looked like an infinity scroll without a data. All table data was preloaded. No table options about paging and scroll helped. If I set virtualizationThreshold > data.length then issue didn't appear and scroll worked nice.

Sorry, can't reproduce it in plunker.
I've found this fix in one of the forked repositories, but that repo was based on grid version 2(ngGrid)

**Comment by Nilanno** [comment]
@JLLeitschuh , toggle "waiting-response" status

**Comment by Havock94** [comment]
The same happens to me and it seems that the more data you load, more space is added.
The scrollbar keeps becoming smaller and smaller but the second half of the grid is empty as @Nilanno screenshot shows. Was it fixed yet?

**Comment by Nilanno** [comment]
@Havock94, there were no new releases since this PR was opened. You can fix it temporarily by patching your local library with a code in this pull request.

**Comment by Nilanno** [comment]
Right now I can't reproduce this issue by rolling back local code, maybe it was a browser bug.
Nevertheless, translateY is a faster than padding in browsers work.

**Comment by irfan** [comment]
Hi All,

Are you planning to merge this PR? Is this PR fixes https://github.com/angular-ui/ui-grid/issues/3747 ?

**Comment by mportuga** [comment]
@dlgski This will have a conflict with Gennadi's PR that changes this logic completely. I suppose we can merge this if we decide not to merge that one. Otherwise we can merge this PR.

**Comment by mportuga** [comment]
@dlgski Actually, I just compared this to the grid scrolling change and they can both be pushed. No conflicts.

**Pull request merged**
