### PR TITLE
feat (i18n): Polish translation.

### PR DESCRIPTION
**Pull request by przemoli**
Polish translation based off english translation.

### CODE REVIEW

**Comment by przemoli** [comment]
Most of actuall translation should be credited to zuk38 in #1951

**Comment by PaulL1** [comment]
Awesome.

**Comment by przemoli** [comment]
When can I expect release with this translation? Can You release it as 3.0.8? Since translations can not be added easily to min.js build of ui-grid, it's somehow pressing topic.

**Comment by PaulL1** [comment]
The releases tend to go every few weeks, and it will be automatically in that release.  I'm not sure at the moment what the plan is for 3.0.8 timing.

**Pull request merged**
