### PR TITLE
Fix (scrollToIfNecessary) - Moving Up Past Top Bound Issues - #4411

### PR DESCRIPTION
**Pull request by dpinho17**
Navigating up past the Top Bound of the grid would sometimes not put the cell into edit mode when using Edit on Cell Nav Feature. This was due to scrollToIfNecessary having a faulty calculation on where to scroll to. This Commit fixes those issues.

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
For some reason the travis check on this never came back.

**Comment by dpinho17** [comment]
Still waiting on this, has anyone looked into it?

**Comment by JLLeitschuh** [comment]
Okay, travis worked. That was strange.

**Comment by mportuga** [comment]
@dpinho17 Can you resolve your merge conflicts?

**Comment by mportuga** [comment]
Closing due to inactivity.

**Pull request closed without merging**
