### PR TITLE
feat(uiGridOdata): new feature for supporting odata protocol

### PR DESCRIPTION
**Pull request by mirik123**
Hi,
I'm the author of OData plugin in free-jqgrid project.
You can see the details here: [grid.odata.js](https://github.com/free-jqgrid/jqGrid/blob/master/plugins/grid.odata.js), [wiki](https://github.com/free-jqgrid/jqGrid/wiki/OData-plugin-for-jqGrid).
After releasing plugin in a stable version I decided to move my steps to the angular project.

The angular ui-grid-odata feature does the following: 
1. queries odata source by the $http provider.
2. parses $metadata response.
3. builds column definitions based on odata metadata
4. when NavigationProperties exist - configures ui-grid-expandable feature and builds multilevel subgrids.

TODO actions:
1. add search filters to odata requests (now available only at client-side filtering)
2. test and fix grid updates
3. fix  ui-grid-expandable bugs:
  * plus signs should not appear when ui-grid-expandable exists but enableExpandable = false
  * filter header doesn't appear in main grid when enableFiltering=true and exists ui-grid-expandable (it still works in subgrids)
  * grid rows cannot be multiline (should have dynamic height)
  * subgrid heights are not calculated correct (should have dynamic height)
  * main grid doesn't change its height when subgrid expands
  * when subgrid expands it drops its shaddow bottomside to the rest of sequential rows, thus they become unclickable.
  * inner multilevel subgrids are not rendered correctly.

Using example:
```javascript
var app = angular.module('app', ['ui.grid', 'ui.grid.expandable', 'ui.grid.odata']);
     app.controller('MainCtrl', ['$scope', 'gridUtil', function ($scope, gridUtil) {
        $scope.myGrid = {
            expandableRowTemplate: 'ui-grid/odataExpandableRowTemplate',
            odata: {
                metadatatype: 'xml',
                datatype: 'json',
                expandable: 'link',
                entitySet: 'Products',
                dataurl: "http://services.odata.org/V4/OData/OData.svc/Products",
                metadataurl: 'http://services.odata.org/V4/OData/OData.svc/$metadata',
                gencolumns: true
            }
        };

        $scope.myGrid.onRegisterApi = function (gridApi) {
            gridApi.expandable.on.rowExpandedStateChanged($scope, function(row) {
                gridUtil.logDebug('expanded: ' + row.entity.Description);
            });

            gridApi.odata.on.success($scope, function(grid) {
                gridUtil.logDebug('succeeded');
            });

            gridApi.odata.on.error($scope, function(data, message) {
                gridUtil.logError(message);
            });
        };
     }]);
```
```html
<div ng-controller="MainCtrl">
     <div id="grid1" ui-grid="myGrid" ui-grid-odata ui-grid-expandable></div>
</div>
```

### CODE REVIEW

**Comment by mirik123** [comment]
I'll add odata.spec.js file later...
replace glyphicon with some other icon already available in angular (need advice).

**Comment by JLLeitschuh** [comment]
You're going to need to squash this into one commit. Also, if your commit messages follow this guideline: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit they will properly be parsed by our changelog generator.

**Comment by JLLeitschuh** [comment]
I'm not sure if this is better as a plugin instead of a built in feature.

**Comment by mirik123** [comment]
I think it is more feature than core part because it highly depends on another ui-grid-expandable feature in order to show subgrids for odata NavigationProperties and ComplexTypes.
If you implement expandable subgrids at core level than odata can also be a core.

Functions uiGridODataService:format and uiGridODataService:concat still can be moved to gridUtil.

Please approve/decline this commit because I would like to develop something on this weekend. 
:)

**Comment by JLLeitschuh** [comment]
Come chat with us about this here: https://gitter.im/angular-ui/ui-grid

**Comment by mirik123** [comment]
will be added to the new ui-grid/features repository...

**Comment by rodrigopivi** [comment]
You sould use Breeze if talking with O-data, I've done some work on implementing a breeze extension for ui-grid, i can totally collaborate in building that again using my previous experience.

**Comment by mirik123** [comment]
Breeze odata format is different from standard odata format supported by http://www.odata.org so, breeze client is 100% compatible only with breeze server.
It also requires including 2 extrernal files - breeze.js and datajs.js
It doesn't support odata v4 - Olingo project is still in beta [olingo.apache.org](http://olingo.apache.org/doc/javascript/index.html).
Whereas my feature is fully selfsufficient and depends only on standard ui-grid features.

It will nice to see pure-angular v3/4 datajs plugin without jquery and other external dependencies.

**Comment by rodrigopivi** [comment]
Hi, i started a project for this https://github.com/rodrigopivi/odataUiGrid it's still at early stages but already comes with odata v3 and v4 support thanks to ODataAngularResources, and the grid already uses filtering, pagination and sorting (still some features missing)

**Comment by mirik123** [comment]
Created repository:  https://github.com/mirik123/ui-grid-odata

**Comment by c0bra** [comment]
@mirik123 

Scripts from raw.githubusercontent.com won't load in because of MIME-type checking. You can change:

`https://raw.githubusercontent.com/mirik123/ui-grid-odata/master/js/ui-grid-odata.js`

to:

`https://rawgit.com/mirik123/ui-grid-odata/master/js/ui-grid-odata.js`

to get it to load.

**Comment by mirik123** [comment]
fixed

**Pull request closed without merging**
