### PR TITLE
Replaced direct dirtyRows access with a getter. Resolves #4022

### LINKED ISSUE #4022: flushDirtyRows causes a JS error when there are no dirty rows
Instead of using the getter, flushDirtyRows tries to access dirtyRows directly. This causes a JS error when there are no dirty rows.

### PR DESCRIPTION
**Pull request by dachev**

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
All tests must pass before we can consider pulling in your code. You can look at the [Developer](https://github.com/angular-ui/ui-grid/blob/master/DEVELOPER.md) guide for details on how to run the tests locally.

**Comment by JLLeitschuh** [comment]
#4022
I'm not 100% certain but I think you can fix this pr by changing
```
grid.rowEdit.getDirtyRows().forEach( function( gridRow ) ...
```
into
```
grid.api.rowEdit.getDirtyRows().forEach( function( gridRow ) ...
```

**Comment by dachev** [comment]
Fixed. I also added a test to verify that no error is thrown in the future.

**Comment by swalters** [comment]
@dachev please rebase your commits into one commit and we'll merge.  If we merge as is, all the commits you have will pollute our commit log. thanks.

**Comment by dachev** [comment]
@swalters done

**Pull request merged**
