### PR TITLE
Styled scrollbars with jquery-scrollbar

### PR DESCRIPTION
**Pull request by mobichel**
Here is small non obtrusive changes allowing to use "styled" scrollbars with help of  [jquery-scrollbar](https://github.com/gromo/jquery.scrollbar) library.

ui-grid continues to use native scrollbars when jquery-scrollbar is not loaded.

+ Demo

### CODE REVIEW

**Comment by mportuga** [comment]
I am sorry, but we want to keep this project free of thirdparty dependencies like this. I would accept a PR for supporting adding a different scrolling library to override the regular scroll bar, but not one that overrides the standard scrollbar by default.

**Comment by mobichel** [comment]
@mportuga thanks for the response. 

Please note that standard scrollbar will work unless you have loaded jquery-scrollbar directive in your app.

Will you accept PR with added ability to specify custom uiGridViewport template and small change from the current PR in the ui-grid.html then I can prepare separate plugin for enabling query-scrollbar in the grid. So project will not be tied with extra third party dependencies?

**Comment by piller187** [comment]
Has this feature been added then?

**Comment by mobichel** [comment]
Here is example how to stlye scrollbar without modification in ui-grid: [example](https://jsfiddle.net/mobichel/qpnfL06n/4/)

**Pull request closed without merging**
