### PR TITLE
chore(build): Updates all dev dependencies

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Updates all of the development dependencies possible.

### CODE REVIEW

**Comment by mportuga** [comment]
@JLLeitschuh Are you still planning on doing this?

**Comment by JLLeitschuh** [comment]
This works, but I couldn't fix the E2E tests. I've tried 3 times now.

**Comment by JLLeitschuh** [comment]
If someone can fix the E2E tests that would be awesome.
I don't have the time to devote to this.

**Comment by mportuga** [comment]
Since this has been stagnated a bit and we have changed other dependencies since, I will decline it for now.

**Pull request closed without merging**
