### PR TITLE
Remove code triggering scroll on each menu select

### PR DESCRIPTION
**Pull request by tirithen**
Each time toggling column visibility with the top right menu the menu is scrolled to the top. This gets impossibly annoying when having 20+ menu items. Once this code (that is mentioned as a "quick fix") is removed it stops scrolling the menu to the top when showing/hiding a column.

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
This is my fault.
However, this isn't really a good solution because it breaks the focus management.
A better solution would be to find a CSS selector to move focus to.
A easy fix would be to add a grid option to disable this.

**Comment by tirithen** [comment]
Sorry I'm new to this project so I do not have a complete overview of what that code should do, is the point visually marking the button triggered as focused?

Should we not use something like this in that case?

    gridUtil.focus.bySelector(angular.element($event.target.parentElement), 'button[type=button]', true);

Take the parent li of $event.target (that is the "clicked" button tag) and pass on this button selector to bySelector method, or maybe just directly do:

    $event.target.focus();

I did try the two methods but the focus does not trigger any visual styling changes, is there a different effect that the "quick fix" was supposed to trigger?

**Comment by tirithen** [comment]
I'm very keen on having this issue solved and included in a ui-grid release as soon as possible to prevent us from having a modified copy of this script in the project that we are currently using ui-grid in.

**Comment by JLLeitschuh** [comment]
That looks like it could solve the issue as well. Give it a shot and tell me if it fixes both of our problems.

**Comment by mportuga** [comment]
@JLLeitschuh @tirithen  What is the status of this?

**Comment by mportuga** [comment]
@JLLeitschuh ?

**Comment by mportuga** [comment]
Closing due to lack of response.

**Pull request closed without merging**
