### PR TITLE
Using glyphs for pagination buttons

### PR DESCRIPTION
**Pull request by salarmehr**
#3506

[Review on Reviewable](https://reviewable.io/reviews/angular-ui/ng-grid/3951)

### CODE REVIEW

**Comment by swalters** [comment]
@salarmehr the build is failing.  the less won't compile.

**Comment by salarmehr** [comment]
@scatcher  May please help me solving the issue. I added the required font to config.json. Should I do any thing more to use it? May you please take a look at the pushed files.

**Comment by JLLeitschuh** [comment]
```
NameError: .ui-grid-icon-play is undefined in src/features/pagination/less/pagination.less on line 59, column 5:
>> 58   .ui-grid-icon-to-previous {
>> 59     .ui-grid-icon-play;
>> 60     filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=2);
```

**Comment by salarmehr** [comment]
@JLLeitschuh running `grunt` executes  the `less` task. However, it should first run `fontello` task. I have no clue about this. May you please shed light on that?

**Comment by salarmehr** [comment]
@PaulL1 May you please help here? grunt runs the less task. However, it should first run fontello task. I have no clue about this. May you please shed light on that?

**Comment by PaulL1** [comment]
Sorry, no idea.  Last time I did font changes I had issues, and I played around with it until it magically worked.  Not sure I ever knew what was wrong or what I fixed.

I'm a bit concerned about `progid:DXImageTransform.Microsoft.BasicImage(rotation=2);`.  Sounds like an IE specific block of code?

**Comment by PaulL1** [comment]
Information sought, no response for some months.  Closing.

**Pull request closed without merging**
