### PR TITLE
#4066 - Fix path to ui-grid.min.css in tutorial/101_intro

### PR DESCRIPTION
**Pull request by ingshtrom**
- Issue #4066 
- this is my first PR on GitHub. ever. Let me know of any incorrect styles or procedures I did not complete. 
- this does NOT fix the script tags that point to css files in all of the tutorial’s source code--that may need to be verified by @c0bra 

Thanks!

### CODE REVIEW

**Comment by swalters** [comment]
@c0bra can you verify that this is an ok change?

**Comment by c0bra** [comment]
`node_modules` doesn't get published anywhere, so no I don't think this is correct.

**Comment by c0bra** [comment]
`<script src="/release/ui-grid.css"></script>` is correct, it's a relative url to http://ui-grid.info/release/ui-grid.css

**Comment by ingshtrom** [comment]
@c0bra Alright, I guess I misread that issue then. I was thinking we were documenting it as if the user brought in UIGrid using NPM, since this isn't actually loading the script for the tutorial page.  So then #4066 should be closed since there isn't an issue there?

**Pull request closed without merging**
