### PR TITLE
apply extraStyle property to give possibility to change style of dedi…

### PR DESCRIPTION
**Pull request by MaksimSimkin**
Hi 
I need a possibility for example to arrange two filters in the column in one row, not below each other as in tutorial. 
Now i am doing it, overriding style ui-grid-filter-container but it applies than for all columns. 
The change i made, adding extra property for a column definition will loose this problem and made grid more variable.

[Review on Reviewable](https://reviewable.io/reviews/angular-ui/ng-grid/3928)

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
I see no problem adding this.

**Comment by MaksimSimkin** [comment]
Added code to fix issue 3985
https://github.com/angular-ui/ng-grid/issues/3985

It's a workaround, but it solves a problem  for ie9.

**Comment by JLLeitschuh** [comment]
Do these need to be rebased before we can merge them in @c0bra?

**Comment by mportuga** [comment]
@MaksimSimkin Can you please resolve the merge conflicts?

**Comment by MaksimSimkin** [comment]
@mportuga conflicts are resolved.

**Comment by JLLeitschuh** [comment]
Looks good!

**Pull request merged**
