### PR TITLE
chore(build): change contents saved to package.json

### LINKED ISSUE #4743: package.json main attribute should be a string
I'm using ui-grid on a nodejs project and it is failing to do a npm publish because it expects package.json main to be a string and currently it is an array

```
npm verb stack TypeError: Path must be a string. Received [ './less',
npm verb stack   './ui-grid.css',
npm verb stack   './ui-grid.eot',
npm verb stack   './ui-grid.js',
npm verb stack   './ui-grid.svg',
npm verb stack   './ui-grid.ttf',
npm verb stack   './ui-grid.woff' ]
npm verb stack     at assertPath (path.js:8:11)
npm verb stack     at Object.win32.resolve (path.js:130:5)
npm verb stack     at Packer.applyIgnores (C:\Program Files\nodejs\node_modules\npm\node_modules\fstream-npm\fstream-npm.js:109:59)
npm verb stack     at Packer.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\fstream-npm\node_modules\fstream-ignore\ignore.js:181:17)
npm verb stack     at Array.filter (native)
npm verb stack     at Packer.IgnoreReader.filterEntries (C:\Program Files\nodejs\node_modules\npm\node_modules\fstream-npm\node_modules\fstream-ignore\ignore.js:179:31)
npm verb stack     at Packer.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\fstream-npm\node_modules\fstream-ignore\ignore.js:92:12)
npm verb stack     at Packer.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\fstream-npm\node_modules\fstream-ignore\ignore.js:134:5)
npm verb stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:76:16
npm verb stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

On older versions of node it was not failing probably because node is now doing some validation, but according to the docs, an array is not valid and it should be a string:
https://docs.npmjs.com/files/package.json#main

The array was added by this issue: https://github.com/angular-ui/ui-grid/issues/3673
It looks as some tool extracts information from the main property of bower.json, but it does not say anything about package.json.
Maybe package.json is generated from bower.json, but some special care should be taken for the main attribute.
I see that in the source, package.json and bower.json are different, in fact, package.json does not contain a main attribute. But when I see my module at src\web-app\bower_components\angular-ui-grid\package.json it looks like bower.json

https://github.com/angular-ui/ui-grid/blob/master/bower.json
https://github.com/angular-ui/ui-grid/blob/master/package.json

For example, bootstrap-bower have different values for main in bower.json and package.json:

https://github.com/angular-ui/bootstrap-bower/blob/master/bower.json

https://github.com/angular-ui/bootstrap-bower/blob/master/package.json

Ohh... After inspecting a bit the code, it looks as the problem is in this task, that is copying the same contents to package.json and bower.json:
https://github.com/angular-ui/ui-grid/blob/9d1a0b46e54983e09e0be8f89f9fac0ee74046e4/lib/grunt/plugins.js#L336

### PR DESCRIPTION
**Pull request by sbruno**
The same contents saved to bower.json were being saved to package.json by the lib\grunt\plugins.js file, generating an invalid package.json since the main attribute was an array instead of a string. Now this has been changed, and the package.json generated for distribution contains the same contents of the package.json file in the source code.

Fixes #4743

### CODE REVIEW

**Comment by logeshilink** [comment]
Hi,

Do you know when this pull will go in to master branch?

**Comment by imbalind** [comment]
@sbruno the code looks good to me, I have to ask you to squash your commits into one, then I'll merge this. Thanks and sorry if it took so long :smiley: !

**Comment by sbruno** [comment]
@imbalind I have never done that. From what I've read the squash is to group many commits in a single one, but my change is just one commit. The others are just merges to update the branch. What should I do? Should I rebase picking all the commits?

**Comment by imbalind** [comment]
@sbruno yeah, I usually rebase following this answer: http://stackoverflow.com/a/5189600/2453383 and then push, as per this answer: http://stackoverflow.com/a/5668050/2453383

**Comment by sbruno** [comment]
@imbalind sorry, I did something but I see no difference. If this is not ok for merging can you apply the changes to some fork of you? The change is very simple.

**Comment by imbalind** [comment]
@sbruno yeah :smile:, I understand how you feel! I had to try several times before getting to know git enough!

**Comment by imbalind** [comment]
Replaced by squashed version: #4976.

**Pull request closed without merging**
