### PR TITLE
update italian translation

### PR DESCRIPTION
**Pull request by francescotrincia**
update italian translation

### CODE REVIEW

**Comment by francescotrincia** [comment]
Hi,
i'm trying to commit this change about italian translation.
During the build I get this error message: **"expected an assignment or function call and instead saw an expression".**

Could anyone help me?

**Comment by francescotrincia** [comment]
I resolved the issue adding /* jshint expr: true */ comment.

**Comment by AgDude** [comment]
This needs to be squashed into a single commit

**Comment by mportuga** [comment]
@francescotrincia Can you please resolve merge conflict?

**Comment by mportuga** [comment]
Closing due to unresolved merge conflicts combined with innactivity

**Pull request closed without merging**
