### PR TITLE
2.x

### PR DESCRIPTION
**Pull request by hanhanx**
We are current using mg-grid in a production project that requires these fixes.

[Review on Reviewable](https://reviewable.io/reviews/angular-ui/ng-grid/2763)

### CODE REVIEW

**Comment by c0bra** [comment]
Looks like this breaks a lot of tests.

**Comment by hanhanx** [comment]
Check in updates to fix test issues.

**Comment by hanhanx** [comment]
Hi, could you please let me know if this pull request can be merge with the branch? My team is waiting for these changes to be in the official build. Thanks.

**Comment by mportuga** [comment]
@hanhanx Is any of this still valid and/or necessary? I realize it has been a while, hence my question. There are also some conflicts in this PR, so I am trying to figure out if it should be closed instead of merged.

**Comment by hanhanx** [comment]
It's been awhile. don't think we need it anymore. You can close it. Thanks.

**Pull request closed without merging**
