### PR TITLE
Fix InvalidStateError in IE10

### PR DESCRIPTION
**Pull request by ajaguar**
Tested in IE10 with pdfmake.js from https://github.com/rouanw/pdfmake/tree/bower because the orginal branch throw an Error

Changes found in: https://github.com/bpampuch/pdfmake/commit/df074b5adb1505fc89918a7963752c7dd791b0eb

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
You need to ensure that jshint passes.

**Comment by JLLeitschuh** [comment]
Please squash and rebase your changes into one commit. Then we will merge. Thank you!

**Comment by JLLeitschuh** [comment]
If you would like your change to show up in the release changelog please change your commit message to match our guidelines:
https://github.com/angular-ui/ui-grid/blob/master/CONTRIBUTING.md#-git-commit-guidelines

**Comment by mportuga** [comment]
This seems like a good change, but it has been inactive for too long. Closing for now. @ajaguar Feel free to open a new PR with this change if you still require it.

**Pull request closed without merging**
