### PR TITLE
Prevent scrollEvent when scroll percentage is greater then 1.

### PR DESCRIPTION
**Pull request by rdkleine**
In the scenario where cell edit and cell navigation is enabled the scrollPercentage will be greater then 1. But this only happens in the bottom row. The check prevents scrolling when this happens.

### CODE REVIEW

**Comment by rdkleine** [comment]
Will add some unittests.

**Comment by mportuga** [comment]
Weird, the karma tests are passing for me. I will take a look when I have a chance.

**Comment by rdkleine** [comment]
Updated my fork. Tests are running again.

**Comment by rdkleine** [comment]
Added coverage for the changes in grid.js.

**Comment by rdkleine** [comment]
Cool thanks!

**Comment by RobPierce** [comment]
This seems to have broken scrollTo - debugging through, when I add a new row to the bottom of my grid, which is off the screen, the scrollToIfNecessary calculates the percentage to scroll to be 1.09 in this particular case and due to this change it means it won't scroll as:

if (percentage <= 1)

is not true. I'm not sure why this change was made but it doesn't seem that the logic is correct - if a row is off the screen then we want to scroll to it; either the logic to determine the percentage value is incorrect or the logic that decides not to scroll if percentage > 1 is wrong.

I'll open a new issue for this and link it.

**Pull request merged**
