### PR TITLE
Romanian language

### PR DESCRIPTION
**Pull request by sMoKeSz**
Added romanian language translation .

### CODE REVIEW

**Comment by sMoKeSz** [comment]
so what should i do now ?

**Comment by PaulL1** [comment]
You need to correct it so that it passes all tests, and then squash those changes so that it's a single commit.

**Comment by sMoKeSz** [comment]
that's not my error i only add a new language .. maybe i should for another branch and not master? what's the newest branch?

**Comment by PaulL1** [comment]
OK, I've restarted the build - it looks like it had an intermittent error on fontello.

**Comment by PaulL1** [comment]
Hmm.  I'm assuming that the fontello error exists on master, and merging anyway.

**Comment by sMoKeSz** [comment]
thank you  for merge, whats the next step to get this commit on angular-ui bower install, cause i need that very much :) (we need that )

**Comment by PaulL1** [comment]
It won’t come through to bower until we cut a new version.  I believe these are going every few weeks, and it will just come through when that happens.

Paul Lambert
Program Director NTS
021 385 488

**Comment by sMoKeSz** [comment]
hello how about next version of ui-grid ?

**Pull request merged**
