### PR TITLE
Update to use or not separator header based on a new grid option and updates unit test

### PR DESCRIPTION
**Pull request by SoyElHomerMalo**
Fixes issue #5517 and updates unit test.

### CODE REVIEW

**Comment by AgDude** [comment]
Please squash commits

**Comment by SoyElHomerMalo** [comment]
Squash done.

**Comment by mportuga** [comment]
@AgDude This looks good to me now and he has addressed your concern about squashing. Is this good to merge?

**Comment by AgDude** [comment]
This looks good to me. However, it will be a breaking change for anyone using default options with IE and a European version of Excel (separator defaults to ";", but we explicitly set it). I will bring up some discussion on the dev channel about upcoming releases and breaking changes.

**Comment by dlgski** [comment]
@SoyElHomerMalo I've attempted a manual merge, but it would be helpful if you could fix the merge conflicts.

thank you

**Comment by SoyElHomerMalo** [comment]
@dlgski Hi! I think I have resolved conflicts. I hope it will be fine now.

**Comment by dlgski** [comment]
looks like there is 1 more conflict?  src/features/exporter/js/exporter.js  Can you take a look?

Thank you!  We will try to include this in 4.0, we are working hard to square away time to get that out this week.

**Comment by dlgski** [comment]
PR #5848 was made to merge in this PR

**Pull request closed without merging**
