### PR TITLE
Excel export 

### PR DESCRIPTION
**Pull request by monster910**
An implementation of excel export using https://github.com/stephenliberty/excel-builder.js. 

This supports fonts, colors, headers, etc... Example is provided in additional ngdoc pages

### CODE REVIEW

**Comment by mportuga** [comment]
@monster910 Could you please fix your build prior to me reviewing this?

**Comment by monster910** [comment]
Done. please review

**Comment by mportuga** [comment]
Thank you! I looked at your code and it looks good. I would like to play with it a bit before merging if you don't mind. I will probably check out your branch at some point this week and see how it works. If you have it live somewhere, that might be even better.

**Comment by monster910** [comment]
I do not have it live. I extended it for a client that has very sophisticated grids with colors, fonts, headers and more... When I get a few minutes, I was going to build another example page in the tutorial with all the bells and whistles.

**Comment by monster910** [comment]
Did you get a chance to merge the code? Also, maybe this week I can build more examples that show a lot more features.

**Comment by mportuga** [comment]
@monster910 Can you resolve conflicts and add a few more unit tests? It didn't seem like many of your new functions were tested currently.

**Comment by monster910** [comment]
Btw, I have several more examples and some unit tests. I will make a new merge request. 

I am also using the code base on a another client with excel export requirements. This one feature was the deciding factor over PrimeNG.

**Pull request merged**
