### PR TITLE
Issue 3923 - Custom Filter is broken

### PR DESCRIPTION
**Pull request by alam123**

### CODE REVIEW

**Comment by c0bra** [comment]
It would be good to have unit tests for this to prevent regressions. Would someone be interested in doing that?

**Comment by JLLeitschuh** [comment]
Closes #3923

**Comment by JLLeitschuh** [comment]
A month without response. Do we want to merge this in and put writing tests for this on the list of todos?

**Comment by JLLeitschuh** [comment]
@alam123 Do you plan to make any other changes?
@c0bra Should we just merge this in?

**Comment by alam123** [comment]
I will try to add a test case over the weekend.

**Comment by JLLeitschuh** [comment]
I'll merge this as there has been no response for a long time.

**Pull request merged**
