### PR TITLE
Update gridValidate.js

### PR DESCRIPTION
**Pull request by basarawu66**
Change parameter memo

### CODE REVIEW

**Comment by mportuga** [comment]
Why are you changing the parameter memo here? Also, please provide an issue

**Comment by phillipspc** [comment]
I opened an issue about this... May just be a documentation error.
https://github.com/angular-ui/ui-grid/issues/5515

**Comment by mportuga** [comment]
@JLLeitschuh @dlgski Do you guys think that we should update the code to match the documentation or the documentation to match the code? I feel like updating the documentation might be better as updating the code would likely break other people who have realized the same thing that @phillipspc realized and wrote their code the way that it is actually behaving.

**Comment by JLLeitschuh** [comment]
Best practice is to always avoid API breaking changes where possible.

**Comment by mportuga** [comment]
This is not the correct fix for this issue. Instead of changing the API, we should fix the documentation.

**Pull request closed without merging**
