### PR TITLE
#6033: This is a proposed fix for the issue where the "selectAll" hea…

### PR DESCRIPTION
**Pull request by wholladay**
…der check is not in sync with the actual selection state of the row. Perhaps this is not the best solution because it couples the selection directive the ui-grid directive. However, this does illustrate a possible solution.

### CODE REVIEW

**Comment by dlgski** [comment]
I'd love to merge this, can you please add unit tests?

**Comment by wholladay** [comment]
@dlgski I would be happy to write some unit tests, but I'm having trouble running the current tests. When I run "npm run test" I get the following:

Running "karmangular" task
Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
Warning: Task "karma:angular-1.4.3" failed. Use --force to continue.

Aborted due to warnings.

**Comment by mportuga** [comment]
@wholladay try just running the grunt task or the grunt dev task, both run unit test for you

**Comment by wholladay** [comment]
@mportuga If I run "grunt dev" I get the following:
```
Running "ngdocs:api" (ngdocs) task
Warning: Unable to read "bower_components/csv-js/csv.js" file (Error code: ENOENT). Use --force to continue.

Aborted due to warnings.
Running "ngdocs:api" (ngdocs) task
Warning: Unable to read "bower_components/csv-js/csv.js" file (Error code: ENOENT). Use --force to continue.

Aborted due to warnings.
```

If I run "grunt dev --force" I get this:
```
Running "karmangular:start" (karmangular) task
Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
Warning: Task "karma:angular-1.4.3:start" failed. Used --force, continuing.
Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
Warning: Task "karma:angular-1.5.0:start" failed. Used --force, continuing.

Running "shell:protractor-start" (shell) task

Running "watch" task
Waiting...[13:11:44] W/start - the out_dir path /Users/wholladay/dev/ui-grid/node_modules/protractor/node_modules/webdriver-manager/selenium does not exist, run webdriver-manager update

```

So, what am I doing wrong?

**Comment by mkell85** [comment]
This is something I would also very much like to see merged.

**Comment by mportuga** [comment]
@wholladay I made a few updates to the package.json over the last couple of weeks. I strongly recommend that you delete your node_modules folder and run npm install, bower install and grunt install

**Comment by wholladay** [comment]
I merged in all the changes from master, removed the node_modules dir, ran npm install, bower install, and grunt install. I'm still getting the same error.

Running "karmangular" task
Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
Warning: Task "karma:angular-1.4.3" failed. Use --force to continue.

Aborted due to warnings.

**Comment by wholladay** [comment]
@dlgski @mportuga Any ideas on this?

**Comment by ian-gallagher** [comment]
I just recently forked this repo. I am getting the same error.

"Running "karmangular:start" (karmangular) task
Loading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
Warning: Task "karma:angular-1.5.0:start" failed. Use --force to continue."

Is this issue fixed?

**Comment by mportuga** [comment]
@wholladay Not sure. I will try to check at some point this week. Sorry, I've been busy and haven't been able to check on UI-Grid for a while. But I am getting back to it this week.

**Comment by mportuga** [comment]
@wholladay What does the machine you use look like? I mean, operating system, IDE, etc. I want to try to mimic your enviroment so that I can hopefully help.

**Pull request merged**
