### PR TITLE
fix(edit): editable cell template fix

### PR DESCRIPTION
**Pull request by dbckr**
Fix cell editing for editable cell templates that contain multiple possible "editors"
(ex: a template that renders either an input or a select by using ng-if directives).

Plunker demonstrating the issue resolved by this fix:
http://plnkr.co/edit/8IuMTZAqFEzrOsBPBJoQ?p=preview

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Do you have any sort of way to test this to prevent regression?

**Comment by dbckr** [comment]
Not presently. I'll see if I can come up with one when I have some time.

**Comment by mportuga** [comment]
@JLLeitschuh It seems fine to me right now and he answered your question. Are you okay with merging this?

**Comment by JLLeitschuh** [comment]
The fields in that plnkr don't revert to the non-edit moder when your click on a different cell to edit them.
Is this expected behaviour?

**Comment by mportuga** [comment]
@dbckr Can you respond to @JLLeitschuh's question?

**Comment by mportuga** [comment]
Closing due to lack of response.

**Pull request closed without merging**
