### PR TITLE
chore: Remove support for angular below 1.4

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Removes all tests and references to support
for angular versions below 1.4

BREAKING CHANGE:
UI Grid is no longer compatible with
angular versions below 1.4

### CODE REVIEW

**Comment by mportuga** [comment]
@JLLeitschuh Please resolve merge conflicts. @dlgski Perhaps we can include this in 3.0?

**Comment by JLLeitschuh** [comment]
I don't know if I have the time. I enabled the `Allow edits from maintainers` feel free to muck with this PR to make it work.

**Comment by dlgski** [comment]
@JLLeitschuh I have resolved your conflicts (just a couple lines in package.json) but I'm not sure github will allow me to push.  Can you fix this PR quickly and let us merge it in so we can promote to 4.0?

**Comment by JLLeitschuh** [comment]
Github will allow you to push to my branch.

**Comment by dlgski** [comment]
unfortunately, it did not:

```
To https://github.com/JLLeitschuh/ui-grid.git
 ! [remote rejected] master -> master (permission denied)
error: failed to push some refs to 'https://github.com/JLLeitschuh/ui-grid.git'
```

**Comment by JLLeitschuh** [comment]
You need to push to my branch `release/v4.0.0`

**Comment by dlgski** [comment]
I was trying to.  Honestly, Jonathan, it's 3 lines in the package.json that are conflicting, you could update your branch yourself very quickly and we can get this released.   Thank you

**Comment by JLLeitschuh** [comment]
Done. Sorry it took me so long.

**Pull request merged**
