### PR TITLE
Option to adjust where the exporter showed up in the menu

### PR DESCRIPTION
**Pull request by jmsunseri**
I added a new option exporterMenuItemOrder for the gridOptions so that I could adjust where the items were showing up in the menu.

### CODE REVIEW

**Comment by jmsunseri** [comment]
Do I need to modify the tests as well?

**Comment by jmsunseri** [comment]
I updated the test and am submitting a new pull request

**Comment by jmsunseri** [comment]
Ok, I'm not sure what this failure indicates.  Please advise.

**Comment by imbalind** [comment]
This is not an error related to your code, no actions are needed by you. We will fix it soon.

**Comment by jmsunseri** [comment]
Thanks!

**Comment by jmsunseri** [comment]
Has this still not been merged in?

**Comment by jmsunseri** [comment]
My first contribution to an open source project finally had been accepted!

**Pull request merged**
