### PR TITLE
fix: clear white space if not exist scrollBar

### PR DESCRIPTION
**Pull request by cybermerlin**
с тестами некогда возиться, если у кого есть желание подправить их - милости прошу.

### CODE REVIEW

**Comment by cybermerlin** [comment]
I have 5 branches for pull request.
hurry please.

**Comment by cybermerlin** [comment]
halo

**Comment by cybermerlin** [comment]
halo

**Comment by cybermerlin** [comment]
hallo

**Comment by JLLeitschuh** [comment]
I see you removed unit tests. Can you add tests that test this?

**Comment by mportuga** [comment]
@cybermerlin IT appears that your most recent changes to this PR caused all tests to fail, can you resolve your issue?

**Comment by cybermerlin** [comment]
I tried, but it did not help

**Comment by mportuga** [comment]
Unfortunately if the travis build is not passing, this PR cannot be merged. I will close it for now, but few free to reopen it if you can figure out how to fix the build issue.

**Pull request closed without merging**
