### PR TITLE
Fix ttf path by removing '?'.  Resolves webpack issue.

### LINKED ISSUE #4113: In the css file:  in@font-face the '?' in url('ui-grid.ttf?') confuses webpack loader
Webpack throws an exception because it does not find the path of 'ttf?'.
When the '?' is removed it works fine

Please remove it if not needed
Thanks

### PR DESCRIPTION
**Pull request by mtraynham**
This fixes #4113. Simple change.

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Can you ensure that this doesn't break on some browser?
http://www.paulirish.com/2009/bulletproof-font-face-implementation-syntax/

**Comment by mtraynham** [comment]
Seems the initial commit had it:
https://github.com/angular-ui/ui-grid/commit/ce330978fe566e9695c30acef04e55221e520960#diff-46456a3b2c603089887395d6c827b689R6

It's just a path reference. Usually you would have query parameters after the `?` to cache bust, like so: `url('ui-grid.ttf?v=20')`

**Comment by mtraynham** [comment]
I'm actually able to resolve this with webpack, but it was a slight hiccup and felt the question mark is unnecessary...

**Comment by JLLeitschuh** [comment]
I'll trust it. I asked some other people with more CSS skills than my own and they approve.

**Comment by mtraynham** [comment]
thanks! :smile:

**Pull request merged**
