### PR TITLE
Fix for: Create ta.js

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Resolves the problems with #3610

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Closes #3610

**Comment by swalters** [comment]
can you squash the commits?

**Comment by JLLeitschuh** [comment]
Haha, I suppose yes.
I don't want to overwrite the commit of the original author though. Does anyone know how I can do that?

**Comment by JLLeitschuh** [comment]
I think I fixed it. And managed to keep the commit author. Woot!

**Pull request merged**
